### ISSUE TITLE
Add "user" tag for call defined user

### ISSUE THREAD

**Issue by ghost** [YSFHQ/phpbb#6]
Soothing, like it used in twitter by <code>@username</code>.

Here is example of proposed message code:
```
Hi, [user]username#1[/user]!

This message special prepared for you and for [user]username#2[/user]!
```

**Comment by EricTendian** [comment]
Can't find any phpBB mods to do this. Feel free to comment with a mod link and I may reopen. Also the `[quote="USERNAME"]` BBCode does notify a user, so that's one workaround to get similar functionality.

**Comment by ghost** [comment]
<code>Hello, [tag]Eric[/tag]!</code>
* https://www.phpbb.com/community/viewtopic.php?f=70&t=2137650

**Comment by EricTendian** [comment]
The one you found won't work because it's for phpBB 3.0, but I found [an extension](https://www.phpbb.com/community/viewtopic.php?f=501&t=2294096) that does it. However, the problem with that one is that it has some performance issues so it won't work well on mobile devices, and a JavaScript error prevents us from using the Discord widget and the plugin at the same time. Once the extension is updated I may enable it.
